### ISSUE TITLE
Add arc welder settings to gcode comments

### ISSUE THREAD

**Issue by oliof** [FormerLurker/ArcWelderLib#1]
Hi,
it would be useful if postprocessed gcode files would reflect the settings used to prostprocess in the comments gcode file, just like slicers add their settings. Something like

```
; postprocessed by [ArcWelder](https://github.com/FormerLurker/ArcWelderLib)
; arc_welder_resolution_mm = 0.05
; arc_welder_g90_influences_extruder = 0
```

**Comment by FormerLurker** [comment]
Yes.  Yes it would.  Great idea, I will do this.

**Comment by FormerLurker** [comment]
This has been completed, thanks for posting and for your pull requests!
