### ISSUE TITLE
Add best fit curve algorithm

### ISSUE THREAD

**Issue by FormerLurker** [FormerLurker/ArcWelderLib#13]
Further improve the curve fitting by reducing the maximum deviation in steps.  Allow this to be enabled/disabled, and provide an argument for determining the number of steps.

**Comment by FormerLurker** [comment]
I tried this, and it did NOT improve much at all.  Not worth the time currently.  Will consider trying this again in the future.

**Comment by kimstik** [comment]
FYI: https://github.com/AlliedToasters/circle-fit/pull/10
