### ISSUE TITLE
Improve curve fitting by testing all points, moving out from the center.

### ISSUE THREAD

**Issue by FormerLurker** [FormerLurker/ArcWelderLib#15]
The previous Arc Welder algorithm created an arc from the middle point when determining if an arc fit the current points.  The new algorithm should check all points.

In a future version I hope to check by length and not by the index of the point.

**Comment by f1vefour** [comment]
It's great to see you are still looking for new optimizations to make this awesome tool better.

**Comment by FormerLurker** [comment]
Thanks @f1vefour!  I've just made some more major improvements ;)
