### ISSUE TITLE
Lot of artifacts

### ISSUE THREAD

**Issue by furynick** [FormerLurker/ArcWelderLib#5]
I tried post-processing on a circular part:
![render_image_original](https://user-images.githubusercontent.com/3520080/87459497-bf9e8b80-c60b-11ea-8eba-f4859c74aade.png)

 but the result is very "noisy"
![render_image_welded](https://user-images.githubusercontent.com/3520080/87459606-e2c93b00-c60b-11ea-8d3b-0d86348d6498.png)

Original g-Code is attached
[CabochonEchelle.zip](https://github.com/FormerLurker/ArcWelderLib/files/4920399/CabochonEchelle.zip)

Command line is the simplest one :
ArcWelderConsole.exe CabochonEchelle.gcode CabochonEchelle-weld.gcode

Using Simplify3D 4.1.2 to slice, Repetier Server 0.93.1 to render.

**Comment by FormerLurker** [comment]
My guess is that your viewer isn't working, though it could be some problem with c++ compilation on your system (I'm relatively new to cross-platform development).  Try viewing your gcode in simplify3d.  Here's what I see after conversion:

![image](https://user-images.githubusercontent.com/33363128/87460700-df658d80-c5d2-11ea-83ca-f3573f22c14b.png)

**Comment by furynick** [comment]
You're right, g-Code looks fine with Simplify visualizer ... I'll try to print it.

**Comment by furynick** [comment]
Simplify doesn't have gyroid nor archimedean (yet), waiting for v5 ...

Print successfull !

**Comment by FormerLurker** [comment]
You could try Slic3r (or Prusa Slicer) or Cura too.  Anyway, enjoy the app!
