### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by kenerwin88** [FormerLurker/ArcWelderLib#65]
Hi,

Sorry I know this isn't the best way to contact someone, but I couldn't find a way to contact a Github user directly.  Just wanted to say thank you for putting so much time into all of your repos, and making them open source and available for anyone to use.  Really, really appreciate it.  Feel free to delete this issue when you see it :).  Have a great day!

Ken

**Comment by FormerLurker** [comment]
Hi @kenerwin88, and thank you very much!  I'm glad you are enjoying my open source projects :)  Also, FYI there is a new discussions tab that may be better for this kind of message, though I don't mind having an open issue for this at all.  Feel free to add a discussion and we can chat.  Thanks again!
